export const beerStyles = [
  "All",
  "Imperial stout",
  "Milk stout",
  "Stout",
  "Irish stout",
  "American IPA",
  "East Coast IPA",
  "West Coast IPA",
  "IPA",
  "DIPA",
  "TIPA",
  "NE IPA",
  "NE DIPA",
  "NE TIPA",
  "DDH IPA",
  "DDH DIPA",
  "DDH TIPA",
  "Milkshake IPA",
  "Kveik IPA",
  "Porter",
  "Baltic porter",
  "English porter",
  "American porter",
  "Barley wine",
  "Mild",
  "Schwarzbier",
  "Amber ale",
  "Flanders red ale",
  "Red ale",
  "Berliner weisse",
  "Lambic",
  "Sour",
  "Witbier",
  "Weissbier",
  "Blonde ale",
  "Hefeweizen",
  "Bock",
  "Brown ale",
  "Doppelbock",
  "Dunkel",
  "Dunkelweizen",
  "Old ale",
  "Oud bruin",
  "Wee heavy",
  "Pale ale",
  "Bitter",
  "Eisbock",
  "British golden ale",
  "Golden ale",
  "Gose",
  "Helles bock",
  "American pale ale",
  "Belgian pale ale",
  "Saison",
  "Kellerbier",
  "California common",
  "German helles",
  "Munich helles",
  "Gueuze",
  "Kolsch",
  "Marzen",
  "Vienna lager",
  "German pils",
  "Czech pilsner",
  "Lager",
  "American lager",
];